logging:
  file.name: ./log/backend.log
  level:
    root: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
  pattern:
    level: r=%X{r} ip=%X{ip} u=%X{u} %5p

spring:
  datasource:
    url: jdbc:h2:file:./database/db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  jpa:
    # Set this property to true if you want to see the executed queries
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        connection:
          provider_disables_autocommit: true
  cache:
    type: simple
  frontend:
    url: http://localhost:4200

file:
  storage:
    base-storage-path: ./uploads
    news-image-path: ./uploads/news-images

security:
  auth:
    header: Authorization
    prefix: "Bearer "
    login-uri: /api/v1/authentication
  jwt:
    secret: ?E(H+MbQeThWmZq4t7w!z%C*F-J@NcRfUjXn2r5u8x/A?D(G+KbPdSgVkYp3s6v9
    type: JWT
    issuer: secure-backend
    audience: secure-app
    # 12 hours in milliseconds
    expiration-time: 43200000

management:
  server:
    port: 8081
  endpoint:
    shutdown:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - shutdown
          - metrics
          - env
  prometheus:
    metrics:
      export:
        enabled: true

---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
  lifecycle:
    timeout-per-shutdown-phase: 30s
  frontend:
    url: https://25ws-se-pr-inso-09-kw57aaouf8kweztfkm5gf.apps.student.inso-w.at
server:
  shutdown: graceful

---
spring:
  config:
    activate:
      on-profile: docker
app:
  image.dir: /app/images/